# Site settings
title: "@deanwrussell"
email: "deanrussell@me.com"
description: "Dean Russell | Always learning web dev, NPR producer and champion of the high-five."
baseurl: ""
url: "http://dean.cool"
twitter_username: deanwrussell
github_username:  deanrussell

# Build settings
markdown: kramdown
permalink: pretty
